import type { Metadata } from "next";
import "./globals.css";
import { craftingStyles } from "galadrielcss";
// Importing the CSS file generated by Galadriel.CSS
import "./layout.css";

export const metadata: Metadata = {
    title: "Galadriel.CSS - Showcasing social media buttons",
    description: "Showcasing social media buttons",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const html = craftingStyles(() => ({
        height: "100vh",
        width: "100vw",
        padding: "0",
        margin: "0",
    }));

    const body = craftingStyles(() => ({
        height: "100%",
        width: "100%",
        padding: "0",
        margin: "0",
    }));

    return (
        <html lang="en" className={html}>
            <body className={body}>{children}</body>
        </html>
    );
}
